CREATE TABLE PRODUCT(
     ID NUMBER PRIMARY KEY,
     NAME NVARCHAR2(30),
     BRAND NVARCHAR2(30),
     PRICE number ,
     COUNT number

 );

CREATE SEQUENCE Product_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PERSON(
    ID NUMBER PRIMARY KEY ,
    NAME NVARCHAR2(20),
    FAMILY NVARCHAR2(20),
    GENDER NVARCHAR2(20),
    BIRTHDATE DATE

);
CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SELL(
    ID NUMBER PRIMARY KEY ,
    PRICE NUMBER,
    SELL_TIME TIMESTAMP,
    OWNER_ID REFERENCES PERSON,
    PRODUCT_ID REFERENCES PRODUCT
);
CREATE SEQUENCE SELL_SEQ START WITH 1 INCREMENT BY 1;


COMMIT ;