CREATE TABLE PRODUCT(
     ID NUMBER PRIMARY KEY,
     NAME NVARCHAR2(30),
     BRAND NVARCHAR2(30),
     PRICE number ,
     COUNT number,
     DELETED number(1) DEFAULT 1

 );

CREATE SEQUENCE Product_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PERSON(
    USERNAME NVARCHAR2(20) PRIMARY KEY ,
    PASSWORD NVARCHAR2(20),
    NAME NVARCHAR2(20),
    FAMILY NVARCHAR2(20),
    GENDER NVARCHAR2(20),
    BIRTHDATE DATE,
    ACTIVE NUMBER(1) DEFAULT 1

);


CREATE TABLE SELL(
    ID NUMBER PRIMARY KEY ,
    PRICE NUMBER,
    SELL_TIME TIMESTAMP,
    USERNAME REFERENCES PERSON,
    PRODUCT_ID REFERENCES PRODUCT,
    DELETED NUMBER(1) DEFAULT 1
);
CREATE SEQUENCE SELL_SEQ START WITH 1 INCREMENT BY 1;


COMMIT ;