CREATE TABLE PRODUCT(
     ID NUMBER PRIMARY KEY,
     NAME NVARCHAR2(30),
     BRAND NVARCHAR2(30),
     PRICE number ,
     COUNT number
 );

CREATE SEQUENCE Product_SEQ START WITH 1 INCREMENT BY 1;